package l9plugins

import (
        "github.com/LeakIX/l9format"
        "github.com/judicieux/boku_plugs/web"
)

var webPlugins = []l9format.WebPluginInterface{
        web.AwsCredentialsHttpPlugin{},
        web.BootstrapHttpPlugin{},
        web.ConfigEnvRubyHttpPlugin{},
        web.ConfigJsonHttp{},
        web.ConfigYmlHttpPlugin{},
        web.DashboardPhpInfoHttpPlugin{},
        web.DockerComposeProdHttpPlugin{},
        web.EnvBackupHttpPlugin{},
        web.EnvBakHttpPlugin{},
        web.EnvConfigHttpPlugin{},
        web.EnvDevelopmentLocalHttpPlugin{},
        web.EnvDevHttpPlugin{},
        web.EnvDevLocalHttpPlugin{},
        web.EnvDistHttpPlugin{},
        web.EnvDockerHttpPlugin{},
        web.EnvExampleHttpPlugin{},
        web.DotEnvHttpPlugin{},
        web.EnvLiveHttpPlugin{},
        web.EnvLocalHttpPlugin{},
        web.EnvOldHttpPlugin{},
        web.EnvPreprodHttpPlugin{},
        web.EnvProdHttpPlugin{},
        web.EnvProdLocalHttpPlugin{},
        web.EnvProductionHttpPlugin{},
        web.EnvProductionLocalHttpPlugin{},
        web.EnvQaHttpPlugin{},
        web.EnvRcHttpPlugin{},
        web.EnvSampleHttpPlugin{},
        web.EnvSaveHttpPlugin{},
        web.EnvStageHttpPlugin{},
        web.EnvStagingLocalHttpPlugin{},
        web.SubApiEnvHttpPlugin{},
        web.SubConfigEnvHttpPlugin{},
        web.EnvTemplateHttpPlugin{},
        web.EnvTestingHttpPlugin{},
        web.EnvTestingLocalHttpPlugin{},
        web.EnvUatHttpPlugin{},
        web.DotGitlabciHttpPlugin{},
        web.ConfigAppHttpPlugin{},
        web.ConfigAssetsHttpPlugin{},
        web.ConfigBackupHttpPlugin{},
        web.ConfigCmsHttpPlugin{},
        web.ConfigCoreHttpPlugin{},
        web.DataConfigHttpPlugin{},
        web.ConfigFilesHttpPlugin{},
        web.GitConfigHttpPlugin{},
        web.ConfigMediaHttpPlugin{},
        web.PublicConfigHttpPlugin{},
        web.ServerConfigHttpPlugin{},
        web.SrcConfigHttpPlugin{},
        web.ConfigStaticHttpPlugin{},
        web.ConfigSubPathApiHttpPlugin{},
        web.ConfigSubPathDevHttpPlugin{},
        web.ConfigSubPathMediaHttpPlugin{},
        web.ConfigSubPathWwwHttpPlugin{},
        web.LinusadminPhpInfoHttpPlugin{},
        web.OldPhpInfoHttpPlugin{},
        web.PInfoHttpPlugin{},
        web.ProfilerPhpInfoHttpPlugin{},
        web.TiretPhpInfoHttpPlugin{},
        web.UnderscorePhpInfoHttpPlugin{},
}

func GetWebPlugins() []l9format.WebPluginInterface {
        return webPlugins
}
